version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: '{{ .Tag }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  disable: true

builds:
  - id: n9e-mcp-server
    main: ./cmd/n9e-mcp-server/
    binary: n9e-mcp-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/n9e/n9e-mcp-server/pkg/version.Version={{ .Tag }}-{{.ShortCommit}}

archives:
  - id: n9e-mcp-server
    name_template: "n9e-mcp-server-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

release:
  github:
    owner: n9e
    name: n9e-mcp-server
  name_template: "v{{ .Version }}"
